export const blogs = [
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/10-intermediate-resources-readingaz',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/close-reading-october-2018',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/december-2016-leveled-books',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/experience-leveled-books',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/experience-reading-a-z-instruction',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/experience-reading-a-z-series',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/improve-struggling-readers-literacy',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/indigenous-peoples-heritage-month-resources',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/march-leveled-books',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/may-2020-leveled-books',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/promote-dual-language-learning',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/read-a-book-day',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/reading-a-z-number-one',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/readingaz-razplus-graphic-books',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/thanksgiving-resources',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/using-file-cabinet-tips',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/veterans-day-leveled-books',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/what-is-guided-reading',
    category1: 'Balanced Literacy',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/your-essa-solution',
    category1: 'Balanced Literacy',
    category2: 'Company News',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/summer-learning-hub',
    category1: 'Balanced Literacy',
    category2: 'Company News',
    category3: 'Writing Instruction',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/nurturing-struggling-readers-high-low-raz-plus',
    category1: 'Balanced Literacy',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/all-about-pumpkins',
    category1: 'Balanced Literacy',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/digital-reading-tools',
    category1: 'Balanced Literacy',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/elevating-reading-development-with-close-reading',
    category1: 'Balanced Literacy',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/gratitude-on-thanksgiving',
    category1: 'Balanced Literacy',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/improving-literacy-childrens-books-with-impact',
    category1: 'Balanced Literacy',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/leveled-books-in-action',
    category1: 'Balanced Literacy',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/poetry-books',
    category1: 'Balanced Literacy',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/veterans-day',
    category1: 'Balanced Literacy',
    category2: 'Writing Instruction',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/blended-learning-close-reading',
    category1: 'Blended Learning',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/blended-learning-razplus',
    category1: 'Blended Learning',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/blended-learning-teacherguide',
    category1: 'Blended Learning',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/dos-donts-blended-learning',
    category1: 'Blended Learning',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/home-school-connection',
    category1: 'Blended Learning',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/learningaz-balances-teaching-technology',
    category1: 'Blended Learning',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/online-learning-for-kids',
    category1: 'Blended Learning',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/path-to-better-blended-learning-series',
    category1: 'Blended Learning',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/razplus-data-conferences',
    category1: 'Blended Learning',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/razplus-reading-proficiency',
    category1: 'Blended Learning',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/remote-learning-webinar',
    category1: 'Blended Learning',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/technology-in-the-classroom',
    category1: 'Blended Learning',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/virtual-learning',
    category1: 'Blended Learning',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/blended-learning-comprehension-skills',
    category1: 'Blended Learning',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/getting-to-know-blended-learning',
    category1: 'Blended Learning',
    category2: 'Balanced Literacy',
    category3: 'Company News',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/blended-learning-hub',
    category1: 'Blended Learning',
    category2: 'Balanced Literacy',
    category3: 'Writing Instruction',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/distance-learning-resources',
    category1: 'Blended Learning',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/integrating-technology-and-social-studies',
    category1: 'Blended Learning',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/support-hybrid-learning',
    category1: 'Blended Learning',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/book-cover-contest-hongkong',
    category1: 'Company News',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/hope-and-literacy',
    category1: 'Company News',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/learningaz-supports-children-in-need',
    category1: 'Company News',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/making-leveled-book',
    category1: 'Company News',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/new-day-for-literacy',
    category1: 'Company News',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/numbers-dont-lie',
    category1: 'Company News',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/teacher-superheroes',
    category1: 'Company News',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/upcoming-events-schedule',
    category1: 'Company News',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/corporate-matching-programs',
    category1: 'Company News',
    category2: 'Funding And Grants',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/autism-awareness-month',
    category1: 'Cultural Responsiveness',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/culturally-responsive-teaching',
    category1: 'Cultural Responsiveness',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/indigenous-mythologies',
    category1: 'Cultural Responsiveness',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/teach-black-history',
    category1: 'Cultural Responsiveness',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/womens-history-month',
    category1: 'Cultural Responsiveness',
    category2: 'Balanced Literacy',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/aapi-heritage-month-2021',
    category1: 'Cultural Responsiveness',
    category2: 'Social-Emotional Learning',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/meaningful-conversations-celebrate-differences',
    category1: 'Cultural Responsiveness',
    category2: 'Social-Emotional Learning',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/understanding-teacher-bias',
    category1: 'Cultural Responsiveness',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/building-data-rich-culture',
    category1: 'Differentiated Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/data-in-education',
    category1: 'Differentiated Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/blended-learning-assessment',
    category1: 'Differentiated Instruction',
    category2: 'Blended Learning',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/2024-predictions',
    category1: 'Differentiated Instruction',
    category2: 'Foundational Skills',
    category3: 'Science of Reading',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/3-tips-support-ells',
    category1: 'Dual Language & ELL',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/6-things-raz-plus-ell-edition',
    category1: 'Dual Language & ELL',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/connect-spanish-culture-raz-plus-espanol',
    category1: 'Dual Language & ELL',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/find-a-new-voice',
    category1: 'Dual Language & ELL',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/raz-plus-authentic-books-to-inspire',
    category1: 'Dual Language & ELL',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/razplus-ell-5-reasons',
    category1: 'Dual Language & ELL',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/unlocking-the-secrets-to-teaching-biliteracy',
    category1: 'Dual Language & ELL',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/top-10-spanish-literacy-resources',
    category1: 'Dual Language & ELL',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/celebrando-el-mes-de-la-herencia-hispana',
    category1: 'Dual Language & ELL',
    category2: 'Cultural Responsiveness',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/parent-involvement-the-key-to-literacy',
    category1: 'Dual Language & ELL',
    category2: 'Tips for Parents',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/foundational-skills-resources',
    category1: 'Foundational Skills',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/readingaz-21st-century-skills',
    category1: 'Foundational Skills',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/teaching-main-idea-comprehension',
    category1: 'Foundational Skills',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/increasing-access-to-grade-level-texts-with-graphic-books',
    category1: 'Foundational Skills',
    category2: 'Balanced Literacy',
    category3: 'Science of Reading',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/pursuing-comprehensive-literacy',
    category1: 'Foundational Skills',
    category2: 'Balanced Literacy',
    category3: 'Science of Reading',
  },
  {
    path: 'https://learninga-z.com/site/resources/breakroom-blog/teacher-take-irion-frake-foundationsa-z',
    category1: 'Foundational Skills',
    category2: 'Reviews',
    category3: 'Science of Reading',
  },
  {
    path: 'https://learninga-z.com/site/resources/breakroom-blog/phonological-awareness-assessments-guide-for-teachers-and-homeschooling-parents',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://learninga-z.com/site/resources/breakroom-blog/phonological-awareness-vs-phonemic-awareness-explained',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://learninga-z.com/site/resources/breakroom-blog/unlocking-the-power-of-phonics-a-comprehensive-guide-for-educators-and-parents',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/benchmark-passages',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/best-phonics-games-for-kindergarten-and-early-elementary-students',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/build-foundational-skills-in-your-district',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/courtneys-teaching-tips-knowledge-building',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/dr-rasinski-art-and-science-of-fluency',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/dr-rasinski-art-and-science-of-reading',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/dr-rasinski-art-and-science-of-teaching-reading-comprehension',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/dr-rasinski-art-and-science-of-word-recognition-phonics',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/elephant-in-the-classroom',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/first-grade-teacher-foundations-a-z',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/foundational-skills-teaching-tips',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/implementing-close-reading-with-research-based-resources',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/jilliam-joe-elephant-in-the-classroom',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/phonological-awareness-vs-phonics',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/rasinski-elephant-in-the-classroom',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/reading-rope-resources',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/revamp-foundational-skills-curriculum',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/teaching-foundational-reading-skills',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://learninga-z.com/site/resources/breakroom-blog/phonics-worksheets-and-games',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/decodable-books',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/engaging-and-educating-with-readers-theater',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/systematic-explicit-instruction-infographic',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/why-social-studies-matters',
    category1: 'Foundational Skills',
    category2: 'Science of Reading',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/combining-social-studies-other-subjects',
    category1: 'Foundational Skills',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/power-project-based-learning-packs-raz-plus',
    category1: 'Foundational Skills',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/inspiring-curiority-taylor-papotto',
    category1: 'Foundational Skills',
    category2: 'Tips for Parents',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/national-book-lovers-day',
    category1: 'Foundational Skills',
    category2: 'Writing Instruction',
    category3: 'Science of Reading',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/the-science-of-writing',
    category1: 'Foundational Skills',
    category2: 'Writing Instruction',
    category3: 'Science of Reading',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/thriving-using-research-based-instruction',
    category1: 'Foundational Skills',
    category2: 'Writing Instruction',
    category3: 'Science of Reading',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/6-grant-writing-guidelines',
    category1: 'Funding And Grants',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/arpa-school-funding',
    category1: 'Funding And Grants',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/cares-act-funding-webinar',
    category1: 'Funding And Grants',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/cares-act-school-funding',
    category1: 'Funding And Grants',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/debunking-titlei-myths',
    category1: 'Funding And Grants',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/argumentation-skill-packs',
    category1: 'Product Updates',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/back-to-school-series',
    category1: 'Product Updates',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/kids-a-z-rostering',
    category1: 'Product Updates',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/kidsaz-customizable-student-avatars',
    category1: 'Product Updates',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/kidsaz-new-intermediate-portal',
    category1: 'Product Updates',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/kidsaz-student-badges',
    category1: 'Product Updates',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/latest-product-updates',
    category1: 'Product Updates',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/raz-kids-constructed-response',
    category1: 'Product Updates',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/raz-plus-assignments-feature',
    category1: 'Product Updates',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/razkids-updates-jan-2018',
    category1: 'Product Updates',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/razplus-updates-jan-2018',
    category1: 'Product Updates',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/writing-a-z-writing-rope',
    category1: 'Product Updates',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/5-razkids-benefits',
    category1: 'Product Updates',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/april-2017-leveled-books',
    category1: 'Product Updates',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/close-read-february-2019',
    category1: 'Product Updates',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/close-read-passages',
    category1: 'Product Updates',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/explore-hollow-kids-series',
    category1: 'Product Updates',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/january-2017-leveled-books',
    category1: 'Product Updates',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/july-2016-leveled-books',
    category1: 'Product Updates',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/june-2017-leveled-books',
    category1: 'Product Updates',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/june-2018-leveled-books',
    category1: 'Product Updates',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/may-2016-leveled-books',
    category1: 'Product Updates',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/new-learning-centers',
    category1: 'Product Updates',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/november-2016-leveled-books',
    category1: 'Product Updates',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/readingaz-updates-jan-2018',
    category1: 'Product Updates',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/spanish-songs-rhymes-books',
    category1: 'Product Updates',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/kidsaz-parent-portal-updates',
    category1: 'Product Updates',
    category2: 'Blended Learning',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/kidsaz-student-experience',
    category1: 'Product Updates',
    category2: 'Blended Learning',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/distance-learning-packs',
    category1: 'Product Updates',
    category2: 'Blended Learning',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/new-meaningful-conversations-resource',
    category1: 'Product Updates',
    category2: 'Cultural Responsivenes',
    category3: 'Social-Emotional Learning',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/kidsaz-new-reading-room',
    category1: 'Product Updates',
    category2: 'Differentiated Instruction',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/nwea-correlations',
    category1: 'Product Updates',
    category2: 'Differentiated Instruction',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/new-spanish-literacy-resources',
    category1: 'Product Updates',
    category2: 'Dual Language & ELL Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/kids-a-z-overview-dashboards',
    category1: 'Product Updates',
    category2: 'Writing Instruction',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/elearning-courses',
    category1: 'Professional Development',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/helping-teachers-make-science-fun',
    category1: 'Professional Development',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/new-years-resolutions',
    category1: 'Professional Development',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/professional-development-support',
    category1: 'Professional Development',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/support-special-education',
    category1: 'Professional Development',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/teacher-blended-learning',
    category1: 'Professional Development',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/transition-into-teaching',
    category1: 'Professional Development',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/what-makes-a-great-teacher',
    category1: 'Professional Development',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/close-reading-intermediate',
    category1: 'Professional Development',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/guided-reading-independence',
    category1: 'Professional Development',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/whyisearlyliteracyessential',
    category1: 'Professional Development',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/5-tips-for-summer-school',
    category1: 'Professional Development',
    category2: 'Balanced Literacy',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/teacher-efficiency-effect-size',
    category1: 'Professional Development',
    category2: 'Balanced Literacy',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/21st-century-writing',
    category1: 'Professional Development',
    category2: 'Balanced Literacy',
    category3: 'Writing Instruction',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/auditing-curriculum-cultural-responsiveness',
    category1: 'Professional Development',
    category2: 'Cultural Responsiveness',
    category3: 'Social-Emotional Learning',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/the-data-story',
    category1: 'Professional Development',
    category2: 'Differentiated Instruction',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/embedded-professional-development-foundations-a-z',
    category1: 'Professional Development',
    category2: 'Foundational Skills',
    category3: 'Science of Reading',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/foundations-a-z-professional-development-to-suit-your-needs',
    category1: 'Professional Development',
    category2: 'Foundational Skills',
    category3: 'Science of Reading',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/learning-from-experts-foundationsa-z',
    category1: 'Professional Development',
    category2: 'Foundational Skills',
    category3: 'Science of Reading',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/professional-development-practice-foundations-a-z',
    category1: 'Professional Development',
    category2: 'Foundational Skills',
    category3: 'Science of Reading',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/the-powerful-duo-a-cut-above-the-competition',
    category1: 'Professional Development',
    category2: 'Foundational Skills',
    category3: 'Science of Reading',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/back-to-school-pack',
    category1: 'Professional Development',
    category2: 'Product Updates',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/professional-development-updates',
    category1: 'Professional Development',
    category2: 'Product Updates',
    category3: 'Company News',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/4d-science-education',
    category1: 'Professional Development',
    category2: 'Science Instruction',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/incorporating-science-learning',
    category1: 'Professional Development',
    category2: 'Science Instruction',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/stem-leadership',
    category1: 'Professional Development',
    category2: 'Science Instruction',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/students-asking-why',
    category1: 'Professional Development',
    category2: 'Science Instruction',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/scienceaz-intermediate-classroom',
    category1: 'Professional Development',
    category2: 'Science Instruction',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/meet-foundations-pd-experts',
    category1: 'Professional Development',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/back-to-school-tips',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/courtneys-teacher-tips',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/create-more-inclusive-classroom',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/creating-an-inclusive-classroom',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/direct-instruction',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/effect-size-series',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/learning-outcomes',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/plentiful-practice',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/reading-challenge-diy',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/spark-connections-with-raz-plus',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/successful-sped-program',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/teacher-clarity',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/teachers-on-teachers-video-series',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/time-saving-tips',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/what-makes-an-effective-teacher',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/world-read-aloud-day',
    category1: 'Professional Development',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/enhancing-homeschooling-efforts',
    category1: 'Professional Development',
    category2: 'Tips for Parents',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/dr-rasinski-district-webinar',
    category1: 'Professional Development',
    category2: 'Vocabulary Instruction',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/dr-rasinski-vocabulary-webinar',
    category1: 'Professional Development',
    category2: 'Vocabulary Instruction',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/vocabulary-webinar-with-dr-rasinski',
    category1: 'Professional Development',
    category2: 'Vocabulary Instruction',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/building-a-community-of-writers-with-writinga-z',
    category1: 'Professional Development',
    category2: 'Writing Instruction',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/transforming-writing-instruction-in-the-classroom',
    category1: 'Professional Development',
    category2: 'Writing Instruction',
    category3: '',
  },
  {
    path: 'https://learninga-z.com/site/resources/breakroom-blog/teacher-take-beiswanger-writinga-z',
    category1: 'Reviews Writing Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/teacher-take-irion-frake-writinga-z',
    category1: 'Reviews Writing Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/10-intermediate-resources-science',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/3d-science-instruction',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/experience-scienceaz-part-one',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/experience-scienceaz-part-three',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/experience-scienceaz-part-two',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/experience-scienceaz-series',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/new-interactive-science-lessons',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-a-z-resources-fun',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-april',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-february-2017',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-january-2018',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-march-2017',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-september-2017',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-process-activities',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/scienceaz-razplus-transformational-teaching',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/support-ngss-scienceaz',
    category1: 'Science Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/4-resources-summer',
    category1: 'Science Instruction',
    category2: 'Balanced Literacy',
    category3: 'Writing Instruction',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/personalized-learning',
    category1: 'Science Instruction',
    category2: 'Balanced Literacy',
    category3: 'Writing Instruction',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/summer-school-certificates',
    category1: 'Science Instruction',
    category2: 'Balanced Literacy',
    category3: 'Writing Instruction',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/winter-classroom-activities',
    category1: 'Science Instruction',
    category2: 'Balanced Literacy',
    category3: 'Writing Instruction',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/winter-new-year-resources',
    category1: 'Science Instruction',
    category2: 'Balanced Literacy',
    category3: 'Writing Instruction',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/blended-learning-scienceaz',
    category1: 'Science Instruction',
    category2: 'Blended Learning',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/learningaz-blended-learning-solution',
    category1: 'Science Instruction',
    category2: 'Blended Learning',
    category3: 'Writing Instruction',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/black-history-month-article',
    category1: 'Science Instruction',
    category2: 'Cultural Responsiveness',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/learningaz-supports-ells',
    category1: 'Science Instruction',
    category2: 'Dual Language & ELL Writing Instruction',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/new-reflections-journal',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/new-storylines-for-ngss',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-eresources',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-april-2018',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-eresources',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-february-2018',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-january-2017',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-july-2017',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-july-2018',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-march-2018',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-may-2017',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-may-2018',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-november-2016',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-november-2017',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-october-2016',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-october-2017',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-september-2016',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-in-the-news-summer-2016',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/take-your-classroom-saz-adventure',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/three-dimensional-learning',
    category1: 'Science Instruction',
    category2: 'Product Updates',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/celebrate-earth-day',
    category1: 'Science Instruction',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/engaging-science-learning',
    category1: 'Science Instruction',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/inquiry-based-instruction',
    category1: 'Science Instruction',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-news-february-2019',
    category1: 'Science Instruction',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/burkins-yates-elephant-in-the-classroom',
    category1: 'Science of Reading',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/dr-rasinski-art-and-science-of-teaching-struggling-readers',
    category1: 'Science of Reading',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/leveled-texts-and-research-based-literacy-support',
    category1: 'Science of Reading',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/science-of-reading-curriculum',
    category1: 'Science of Reading',
    category2: '',
    category3: '',
  },
  {
    path: 'https://learninga-z.com/site/resources/breakroom-blog/3-step-sor-read-aloud',
    category1: 'Science of Reading',
    category2: 'Social-Emotional Learning',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://learninga-z.com/site/resources/breakroom-blog/pros-and-cons-adaptive-literacy-programs',
    category1: 'Science of Reading',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://learninga-z.com/site/resources/breakroom-blog/teacher-led-instruction',
    category1: 'Science of Reading',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/boosting-reading-comprehension-raz-plus',
    category1: 'Science of Reading',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/maintaining-reading-development-over-the-holidays',
    category1: 'Science of Reading',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/value-of-teacher-grant-program',
    category1: 'Science of Reading',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/bullying-prevention',
    category1: 'Social-Emotional Learning',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/fostering-social-emotional-learning',
    category1: 'Social-Emotional Learning',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/unicef-kid-power-2021',
    category1: 'Social-Emotional Learning',
    category2: 'Company News',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/unicef-kid-power-2022',
    category1: 'Social-Emotional Learning',
    category2: 'Company News',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/unicef-kidpower-giveback',
    category1: 'Social-Emotional Learning',
    category2: 'Company News',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/unicef-ukraine-donation',
    category1: 'Social-Emotional Learning',
    category2: 'Company News',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/we-are-all-marvelous',
    category1: 'Social-Emotional Learning',
    category2: 'Company News',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/2022-star-donation-challenge',
    category1: 'Social-Emotional Learning',
    category2: 'Foundational Skills',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/fall-2023-star-donation-challenge-results',
    category1: 'Social-Emotional Learning',
    category2: 'Foundational Skills',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/learning-a-z-star-donation-challenge',
    category1: 'Social-Emotional Learning',
    category2: 'Foundational Skills',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/spring-2024-star-donation-challenge-results',
    category1: 'Social-Emotional Learning',
    category2: 'Foundational Skills',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/parents-can-set-students-up-for-success',
    category1: 'Social-Emotional Learning',
    category2: 'Foundational Skills',
    category3: 'Tips for Parents',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/3-step-sor-read-aloud',
    category1: 'Social-Emotional Learning',
    category2: 'Science of Reading',
    category3: 'Teaching Resources',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/sel-activities-thanksgiving',
    category1: 'Social-Emotional Learning',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/sel-conversations-kit',
    category1: 'Social-Emotional Learning',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/social-emotional-learning-guide',
    category1: 'Social-Emotional Learning',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/promoting-mental-health-classroom',
    category1: 'Teacher Wellness',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/reducing-teacher-burnout',
    category1: 'Teacher Wellness',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/celebrating-teacher-appreciation-week-2023',
    category1: 'Teacher Wellness',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/aesops-fables-book-text',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/arts-integration-improving-classroom-activities',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/build-welcoming-classroom-tasha-fisher',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/celebrate-independence-day',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/celebrating-you-teacher-appreciation-week',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/classroom-tidying-tips',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/closing-the-gap',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/doing-the-right-thing-book-text',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/easy-fun-video-series',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/effective-lesson-plans',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/encourage-summertime-reading',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/engage-empower-students-level-up',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/engaging-students-with-interactive-learning',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/establish-strong-classroom-community-tasha-fisher',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/gaining-insight-into-the-teacher-experience',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/gear-up-summer-reading',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/getting-dressed-book-content',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/growth-oriented-thinkers-tasha-fisher',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/halloween-resources',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/importance-of-feedback',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/improving-reading-comprehension',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/increase-student-engagement-with-raz-plus',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/knowledge-based-and-skill-based-learning',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/learningaz-halloween-resources',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/literacy-instruction-tips',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/maintaining-motivation-alejandra-londono',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/national-reading-month',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/project-based-learning',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/raz-plus-connected-classroom',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/raz-plus-digital-books-with-purpose',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/safe-halloween-tips',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/school-at-home-tips',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/storytelling-tips-and-reading-questions',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/student-behavior-charts-for-educators',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/teacher-appreciation-gifts',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/teacher-reimbursement-for-school-purchases',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/thankful-40-things',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/top-february-resources',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/vision-board',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/volunteer-tutoring',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/what-season-is-it-book-text',
    category1: 'Teaching Resources',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/fun-books-for-summer',
    category1: 'Teaching Resources',
    category2: 'Balanced Literacy',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/teaching-resources-you-can-trust',
    category1: 'Teaching Resources',
    category2: 'Online Teaching Resources',
    category3: '',
  },
  {
    path: 'https://learninga-z.com/site/resources/breakroom-blog/srsd-writing-process',
    category1: 'Teaching Resources',
    category2: 'Writing Instruction',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/benefits-of-homeschooling',
    category1: 'Tips for Parents',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/fluency-passages',
    category1: 'Tips for Parents',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/homeschool-curriculum-and-program-resources',
    category1: 'Tips for Parents',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/supplies-necessary-for-homeschooling',
    category1: 'Tips for Parents',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/5day-vocabulary-lesson-plan',
    category1: 'Vocabulary Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/building-vocabulary',
    category1: 'Vocabulary Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/new-vocabulary-a-z',
    category1: 'Vocabulary Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/vocabulary-practice-infographic',
    category1: 'Vocabulary Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/why-vocabulary-matters',
    category1: 'Vocabulary Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/learningaz-trials',
    category1: 'Vocabulary Instruction',
    category2: 'Science Instruction',
    category3: 'Balanced Literacy',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/well-rounded-education',
    category1: 'Vocabulary Instruction',
    category2: 'Science Instruction',
    category3: 'Balanced Literacy',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/dr-rasinski-art-and-science-of-vocabulary',
    category1: 'Vocabulary Instruction',
    category2: 'Science of Reading',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/5-fun-ways-vocabularyaz',
    category1: 'Vocabulary Instruction',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/free-rasinski-vocabulary-whitepaper',
    category1: 'Vocabulary Instruction',
    category2: 'Teaching Resources',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/back-to-school-writing',
    category1: 'Writing Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/examining-the-impact-on-the-world-of-education',
    category1: 'Writing Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/getting-to-know-writing-a-z',
    category1: 'Writing Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/taking-the-guesswork-out-of-writing-instruction',
    category1: 'Writing Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/teacher-grant-program',
    category1: 'Writing Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/the-importance-of-writing-instruction',
    category1: 'Writing Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/writingaz-critical-thinking',
    category1: 'Writing Instruction',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/avatar-contest-winners',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/back-to-school-goals',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/back-to-school-updates',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/classic-books',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/experience-leveled-reading-practice',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/experience-raz-kids-series',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/experience-razplus-part-one',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/experience-razplus-part-three',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/experience-razplus-part-two',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/experience-razplus-series',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/file-cabinet-curriculum-collaboration',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/fishing-in-the-rain-book-text',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/founding-of-the-appalachian-trail-book-text',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/hispanic-heritage-month-2017',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/holiday-weekend-reads',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/how-the-camel-got-his-hump-book-text',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/personalized-learning-thehuman-connection',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/pirate-ships-and-flags-book-text',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/places-people-live-book-text',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/planning-summer-school',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/purposeful-classroom-discourse',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/raz-kids-better-reading',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/raz-kids-practice-reading',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/razplus-black-history-resources',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/razplus-close-reading-packs',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/razplus-read-across-america',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/razplus-summer-school-theme-packs',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/razplus-world-leaders',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/simplifying-summer-school-with-raz-plus',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/six-billion-books-read',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/summer-school-activities-razplus',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/teaching-resources-arent-all-created-equal',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/thinking-about-human-brains',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/updated-razplus-features',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/year-in-review',
    category1: '',
    category2: '',
    category3: '',
  },
  {
    path: 'https://www.learninga-z.com/site/resources/breakroom-blog/year-in-review-2022',
    category1: '',
    category2: '',
    category3: '',
  },
];

export const blogVideos = [
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/best-phonics-games-for-kindergarten-and-early-elementary-students',
    video1: 'https://www.youtube.com/shorts/dxz2_N97Zxg?feature=share',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/unlocking-the-power-of-phonics-a-comprehensive-guide-for-educators-and-parents',
    video1: 'https://player.vimeo.com/video/873878162',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/phonological-awareness-assessments-guide-for-teachers-and-homeschooling-parents',
    video1: 'https://youtu.be/o07gkNYYf60',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/phonological-awareness-vs-phonics',
    video1: 'https://youtu.be/RAUkpAzx3ZE',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/phonological-awareness-assessments-guide-for-teachers-and-homeschooling-parents',
    video1: 'https://youtu.be/o07gkNYYf60',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/phonological-awareness-vs-phonemic-awareness-explained',
    video1: 'https://youtu.be/7mviYcY-jrU',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/phonics-worksheets-and-games',
    video1: 'https://youtu.be/4EbshX8sy6c',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/integrating-technology-and-social-studies',
    video1: 'Video no longer exists, that part of this blog can be removed',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/easy-fun-video-series',
    video1: 'https://youtu.be/v5UdTyIm018',
    video2: 'https://youtu.be/3Hzn8UL3QJ8',
    video3: 'https://youtu.be/0U77ZPgB0X0',
    video4: 'https://youtu.be/3ksPV3x_NYI',
    video5: 'https://youtu.be/lFgLBPBdj0Y',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/elephant-in-the-classroom',
    video1: 'https://vimeo.com/730388549',
    video2: 'https://vimeo.com/727584888',
    video3: 'https://vimeo.com/727584966',
    video4: 'https://vimeo.com/727584815',
    video5: 'https://vimeo.com/718412605',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/jilliam-joe-elephant-in-the-classroom',
    video1: 'https://vimeo.com/730380240',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/burkins-yates-elephant-in-the-classroom',
    video1: 'https://vimeo.com/730376676',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/rasinski-elephant-in-the-classroom',
    video1: 'https://vimeo.com/725754685',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/first-grade-teacher-foundations-a-z',
    video1: 'https://vimeo.com/718412605',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/raz-plus-authentic-books-to-inspire',
    video1: 'https://vimeo.com/475526578',
    video2: 'https://vimeo.com/475515359',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/professional-development-practice-foundations-a-z',
    video1: 'https://player.vimeo.com/video/686069866',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/increase-student-engagement-with-raz-plus',
    video1: 'https://player.vimeo.com/video/678289105?h=9ebb3c039d',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/learning-from-experts-foundationsa-z',
    video1: 'https://player.vimeo.com/video/671280108?h=db84457933',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/dr-rasinski-art-and-science-of-reading',
    video1: 'https://player.vimeo.com/video/592958014?h=562c3955b3',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/nwea-correlations',
    video1: 'https://player.vimeo.com/video/549387698?h=4dd8d22e5b',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/teachers-on-teachers-video-series',
    video1: 'https://youtu.be/CCrdG4afTO8',
    video2: 'https://youtu.be/qGfVsF62aOg',
    video3: 'https://youtu.be/3wo1Kp_eY-Y',
    video4: 'https://youtu.be/pAIRuuPjJVU',
    video5: 'https://youtu.be/3nXUf7nVjFg',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/teach-black-history',
    video1: 'https://youtu.be/pAIRuuPjJVU',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/encourage-summertime-reading',
    video1: 'https://youtu.be/Gb8QP-lrAq0?feature=shared',
    video2: 'https://youtu.be/pa1AMbFwDaY?feature=shared',
    video3: 'https://youtu.be/AzkpJdRAu9Q?feature=shared',
    video4: 'https://youtu.be/HngTh-lidPg?feature=shared',
    video5: 'https://youtu.be/coNwR7kTJKY?feature=shared',
    video6: 'https://youtu.be/xhpfbYvKyLY?feature=shared',
    video7: 'https://youtu.be/jJo1ypkJXc8?feature=shared',
    video8: 'https://youtu.be/s0Io7ARKmgY?feature=shared',
    video9: 'https://youtu.be/16vxhkopKEg?feature=shared',
    video10: 'https://youtu.be/dYk7ZTFCfcw?feature=shared',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/explore-hollow-kids-series',
    video1: 'https://vimeo.com/1012095203',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/back-to-school-updates',
    video1: 'https://vimeo.com/462771309',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/making-leveled-book',
    video1: 'https://player.vimeo.com/video/1012069162?h=4dd8d22e5b',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/new-spanish-literacy-resources',
    video1: 'https://youtu.be/AMAJ7EzVw7A?feature=shared',
    video2: 'https://vimeo.com/1012072070',
    video3: 'https://youtu.be/ZmU7zb5QVtI?feature=shared',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/kidsaz-parent-portal-updates',
    video1: 'https://vimeo.com/1012121390',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/close-read-passages',
    video1: 'https://youtu.be/ZmU7zb5QVtI',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/10-intermediate-resources-readingaz',
    video1: 'https://vimeo.com/1012109136',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/take-your-classroom-saz-adventure',
    video1: 'https://player.vimeo.com/video/916039976?h=4dd8d22e5b',
    video2: 'https://player.vimeo.com/video/916013479?h=4dd8d22e5b',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/razplus-summer-school-theme-packs',
    video1: 'https://player.vimeo.com/video/797520986?h=4dd8d22e5b',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/readingaz-21st-century-skills',
    video1: 'https://player.vimeo.com/video/1012117809?h=4dd8d22e5b',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
  {
    link: 'https://www.learninga-z.com/site/resources/breakroom-blog/new-day-for-literacy',
    video1: 'https://player.vimeo.com/video/1012066735?h=4dd8d22e5b',
    video2: '',
    video3: '',
    video4: '',
    video5: '',
    video6: '',
    video7: '',
    video8: '',
    video9: '',
    video10: '',
  },
];
