export const videos = [
  {
    Parent: '',
    Subcategory: 'Company Videos [-10]',
    Videosundercategory: '',
    Videocategories: '',
    YTandVimeoLinks: '',
    UpdatedtoEmbededvideo: '',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/what-is-learningaz?cache=0',
    Videocategories: 'Learning A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=o07gkNYYf60&list=PLGcuN9fntXERGKDg4dUp3KHs0rrnWoF2I&index=1',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/sor-essentials?cache=0',
    Videocategories: 'Learning A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=7mviYcY-jrU',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/learning-a-z-glance?cache=0',
    Videocategories: 'Learning A-Z',
    YTandVimeoLinks: 'https://vimeo.com/1012066735?share=copy#t=0',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/making-learning-a-z-book?cache=0',
    Videocategories: 'Learning A-Z, Raz-Plus, Reading A-Z',
    YTandVimeoLinks: 'https://vimeo.com/1012069162?share=copy#t=0',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/learning-a-z-mission?cache=0',
    Videocategories: 'Learning A-Z',
    YTandVimeoLinks: 'https://vimeo.com/472390449',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/summer-learning-scavenger-hunt?cache=0',
    Videocategories: 'Learning A-Z, Raz-Kids, Raz-Plus, Reading A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=s0Io7ARKmgY&list=PLGcuN9fntXEToNAiHzWjAZG47WWplVpib&index=8&pp=iAQB',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/summer-learning-word-work?cache=0',
    Videocategories: 'Learning A-Z, Raz-Kids, Raz-Plus, Reading A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=coNwR7kTJKY&list=PLGcuN9fntXEToNAiHzWjAZG47WWplVpib&index=5&pp=iAQB',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/summer-learning-read-alouds?cache=0',
    Videocategories: 'Learning A-Z, Raz-Kids, Raz-Plus, Reading A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=pa1AMbFwDaY&list=PLGcuN9fntXEToNAiHzWjAZG47WWplVpib&index=2&pp=iAQB',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/summer-learning-writing?cache=0',
    Videocategories: 'Learning A-Z, Raz-Kids, Raz-Plus, Reading A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=16vxhkopKEg&list=PLGcuN9fntXEToNAiHzWjAZG47WWplVpib&index=9&pp=iAQB',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/summer-learning-print-rich-environments?cache=0',
    Videocategories: 'Learning A-Z, Raz-Kids, Raz-Plus, Reading A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=xhpfbYvKyLY',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/summer-learning-reading-strategies?cache=0',
    Videocategories: 'Learning A-Z, Raz-Kids, Raz-Plus, Reading A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=AzkpJdRAu9Q&list=PLGcuN9fntXEToNAiHzWjAZG47WWplVpib&index=3&pp=iAQB',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/summer-learning-non-fiction?cache=0',
    Videocategories: 'Learning A-Z, Raz-Kids, Raz-Plus, Reading A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=dYk7ZTFCfcw&list=PLGcuN9fntXEToNAiHzWjAZG47WWplVpib&index=10&pp=iAQB',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/summer-learning-following-an-author?cache=0',
    Videocategories: 'Learning A-Z, Raz-Kids, Raz-Plus, Reading A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=jJo1ypkJXc8&list=PLGcuN9fntXEToNAiHzWjAZG47WWplVpib&index=7&pp=iAQB',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/summer-learning-school-home-connection?cache=0',
    Videocategories: 'Learning A-Z, Raz-Kids, Raz-Plus, Reading A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=HngTh-lidPg&list=PLGcuN9fntXEToNAiHzWjAZG47WWplVpib&index=4&pp=iAQB',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/summer-learning-reading-everyday?cache=0',
    Videocategories: 'Learning A-Z, Raz-Kids, Raz-Plus, Reading A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=Gb8QP-lrAq0&list=PLGcuN9fntXEToNAiHzWjAZG47WWplVpib&index=1&pp=iAQB',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/spanish-book-author-tanya?cache=0',
    Videocategories: 'Raz-Plus, Raz-Plus ELL, Reading A-Z',
    YTandVimeoLinks: 'https://vimeo.com/475526578',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/spanish-book-author-jorge?cache=0',
    Videocategories: 'Raz-Plus, Raz-Plus ELL, Reading A-Z',
    YTandVimeoLinks: 'https://vimeo.com/475515359',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/spanish-book-author-claudia?cache=0',
    Videocategories: 'Raz-Plus, Raz-Plus ELL, Reading A-Z',
    YTandVimeoLinks: 'https://vimeo.com/475520670',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: 'FAZ Videos [2]',
    Videosundercategory: '',
    Videocategories: '',
    YTandVimeoLinks: '',
    UpdatedtoEmbededvideo: '',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/foundations-a-z-science-of-reading?cache=0',
    Videocategories: 'Foundations A-Z',
    YTandVimeoLinks: 'https://vimeo.com/696728060',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/powerful-duo-literacy-block?cache=0',
    Videocategories: 'Foundations A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=nXamEKN1YT0',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/foundations-a-z-teacher-support?cache=0',
    Videocategories: 'Foundations A-Z',
    YTandVimeoLinks: 'https://vimeo.com/696732464',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/foundationsa-z-explore-zone?cache=0',
    Videocategories: 'Foundations A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=sXfAOk9TGI0',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/foundations-a-z-engaging-student-resources?cache=0',
    Videocategories: 'Foundations A-Z',
    YTandVimeoLinks: 'https://vimeo.com/1012070819?share=copy#t=0',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/foundationsa-z-overview?cache=0',
    Videocategories: 'Foundations A-Z',
    YTandVimeoLinks: 'https://vimeo.com/940930662',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/foundations-a-z-raz-plus-powerful-duo?cache=0',
    Videocategories: 'Foundations A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=4EbshX8sy6c&list=PLGcuN9fntXESzYeHRwYoybV87AlKIHUyW&index=19',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/foundations-a-z-complements-core-curriculum?cache=0',
    Videocategories: 'Foundations A-Z',
    YTandVimeoLinks: 'https://vimeo.com/696728343',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/integrated-knowledge-building-in-foundations-a-z?cache=0',
    Videocategories: 'Foundations A-Z',
    YTandVimeoLinks: 'https://vimeo.com/771269648',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/introducing-foundationsa-z?cache=0',
    Videocategories: 'Foundations A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=SmoOr52BNBU',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/first-grade-teacher-foundations-a-z?cache=0',
    Videocategories: 'Foundations A-Z, Testimonials',
    YTandVimeoLinks: 'https://vimeo.com/718413398',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/rasinski-elephant-in-the-classroom?cache=0',
    Videocategories: 'Foundations A-Z',
    YTandVimeoLinks: 'https://vimeo.com/725754685',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/burkins-yates-elephant-in-the-classroom?cache=0',
    Videocategories: 'Foundations A-Z',
    YTandVimeoLinks: 'https://vimeo.com/730376676',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/jilliam-joe-elephant-in-the-classroom?cache=0',
    Videocategories: 'Foundations A-Z',
    YTandVimeoLinks: 'https://vimeo.com/730380240',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: 'RP Videos [5]',
    Videosundercategory: '',
    Videocategories: '',
    YTandVimeoLinks: '',
    UpdatedtoEmbededvideo: '',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/raz-plus-decodables?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=rsj1DdnqeIQ&list=PLGcuN9fntXESzYeHRwYoybV87AlKIHUyW&index=16',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/raz-plus-overview?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://vimeo.com/644492825',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/raz-plus-content-area?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=fW5t4IjTnPQ&list=PLGcuN9fntXESzYeHRwYoybV87AlKIHUyW&index=17',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/raz-plus-at-a-glance?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://vimeo.com/569525730',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/raz-plus-multilingual?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=pf09iigsENo&list=PLGcuN9fntXESzYeHRwYoybV87AlKIHUyW&index=18',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/raz-plus-essentials?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=Y2j4JflQhR4&list=PLGcuN9fntXESzYeHRwYoybV87AlKIHUyW&index=12',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/razplus-spanish-closereadingpacks?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=ZmU7zb5QVtI',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/raz-plus-authentic-spanish?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://vimeo.com/1012072070',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/raz-plus-project-based-learning?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=09UfCAjvLGM',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/raz-plus-summer-school?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://vimeo.com/797520986',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/meaningful-conversations?cache=0',
    Videocategories: 'Raz-Plus, Reading A-Z',
    YTandVimeoLinks: 'https://vimeo.com/581374137',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/razplus-reading-copilot?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=etQ7hMV2ztE&list=PLGcuN9fntXESzYeHRwYoybV87AlKIHUyW&index=4',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/raz-plus-close-read-summary?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://player.vimeo.com/video/1008609095?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/raz-plus-ell-edition-overview?cache=0',
    Videocategories: 'Raz-Plus, Raz-Plus ELL',
    YTandVimeoLinks: 'https://vimeo.com/462769305',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/raz-plus-etools?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://vimeo.com/1012073140',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/raz-plus-close-reading?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://vimeo.com/1012074488',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/raz-plus-espanol-overview?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=x6QiEp4N4-Q',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/raz-plus-nwea-map-growth?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://vimeo.com/549387698',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/raz-plus-argumentation?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://vimeo.com/1012075537',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/raz-plus-pbl-classroom?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://vimeo.com/1012079187',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/raz-plus-paired-book?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://vimeo.com/1012091675',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/raz-plus-reading-instruction?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=SYTB39vUS-I&list=PLGcuN9fntXESzYeHRwYoybV87AlKIHUyW&index=5',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/raz-plus-nwea-map-growth-clever?cache=0',
    Videocategories: 'Raz-Plus',
    YTandVimeoLinks: 'https://vimeo.com/549385056',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: 'Raz-Plus Connected Classroom Videos [6]',
    Videosundercategory: '',
    Videocategories: '',
    YTandVimeoLinks: '',
    UpdatedtoEmbededvideo: '',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/raz-plus-connected-classroom?cache=0',
    Videocategories: 'Raz-Plus Connected Classroom',
    YTandVimeoLinks: 'https://vimeo.com/901985290',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: 'RAZ Videos [8]',
    Videosundercategory: '',
    Videocategories: '',
    YTandVimeoLinks: '',
    UpdatedtoEmbededvideo: '',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/reading-a-z-fluency-practice?cache=0',
    Videocategories: 'Reading A-Z',
    YTandVimeoLinks: 'https://vimeo.com/1012094180',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/hollow-kids-series?cache=0',
    Videocategories: 'Reading A-Z, Raz-Plus',
    YTandVimeoLinks: 'https://vimeo.com/1012095203',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/readinga-z-find-resources?cache=0',
    Videocategories: 'Reading A-Z',
    YTandVimeoLinks: 'https://vimeo.com/1012096611',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/readinga-z-project-based-learning?cache=0',
    Videocategories: 'Reading A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=fvRhWAup9qk&list=PLGcuN9fntXEQGtzMkmhdgrLietNRMgV_B&index=5',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/readinga-z-summer-school?cache=0',
    Videocategories: 'Reading A-Z',
    YTandVimeoLinks: 'https://vimeo.com/1012105956',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/readinga-z-paired-book?cache=0',
    Videocategories: 'Reading A-Z',
    YTandVimeoLinks: 'https://vimeo.com/1012107254',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/reading-a-z-pbl-classroom?cache=0',
    Videocategories: 'Reading A-Z',
    YTandVimeoLinks: 'https://vimeo.com/1012109136',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/reading-a-z-overview?cache=0',
    Videocategories: 'Reading A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=uOdTv-ZvGKc&list=PLGcuN9fntXEQGtzMkmhdgrLietNRMgV_B&index=3',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/reading-a-z-close-reading?cache=0',
    Videocategories: 'Reading A-Z',
    YTandVimeoLinks: 'https://vimeo.com/1012117809',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/reading-a-z-comprehension-packs?cache=0',
    Videocategories: 'Reading A-Z',
    YTandVimeoLinks: 'https://vimeo.com/1012119360',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/hollow-kids-finale?cache=0',
    Videocategories: 'Reading A-Z, Raz-Plus',
    YTandVimeoLinks: 'https://vimeo.com/1012118920',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: 'RK Videos [18]',
    Videosundercategory: '',
    Videocategories: '',
    YTandVimeoLinks: '',
    UpdatedtoEmbededvideo: '',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/student-portal-features-incentives?cache=0',
    Videocategories: 'Raz-Kids, Kids A-Z, Raz-Plus, Science A-Z, Vocabulary A-Z, Writing A -Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=J--k2FPp3ag&list=PLGcuN9fntXERvHxcoO4rd7Jsx7lyboAC2&index=6',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/raz-kids-at-a-glance?cache=0',
    Videocategories: 'Raz-Kids',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=KVC1ybWLSEY&list=PLGcuN9fntXESTKoFQyTET3hpMmhQCXVfz&index=3',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/raz-kids-ebook-tools?cache=0',
    Videocategories: 'Raz-Kids',
    YTandVimeoLinks: 'https://vimeo.com/1012120409',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: 'SAZ Videos [38]',
    Videosundercategory: '',
    Videocategories: '',
    YTandVimeoLinks: '',
    UpdatedtoEmbededvideo: '',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/interactive-science-lessons?cache=0',
    Videocategories: 'Science A-Z',
    YTandVimeoLinks: 'https://vimeo.com/916013479',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/science-a-z-overview?cache=0',
    Videocategories: 'Science A-Z',
    YTandVimeoLinks: 'https://vimeo.com/644494855',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/science-project-based-learning?cache=0',
    Videocategories: 'Science A-Z',
    YTandVimeoLinks: 'https://vimeo.com/1012097621',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/science-a-z-at-a-glance?cache=0',
    Videocategories: 'Science A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=9rRjl7cDgFo&list=PLGcuN9fntXERvHxcoO4rd7Jsx7lyboAC2&index=3',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/scienceaz-storylines?cache=0',
    Videocategories: 'Science A-Z',
    YTandVimeoLinks: 'https://vimeo.com/916047791',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/saz-adventures?cache=0',
    Videocategories: 'Science A-Z',
    YTandVimeoLinks: 'https://vimeo.com/916039976',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: 'WAZ Videos [48]',
    Videosundercategory: '',
    Videocategories: '',
    YTandVimeoLinks: '',
    UpdatedtoEmbededvideo: '',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/writing-a-z-lesson-plans?cache=0',
    Videocategories: 'Writing A-Z',
    YTandVimeoLinks: 'https://vimeo.com/838362908',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/meetwaltwritingandlearningtogether?cache=0',
    Videocategories: 'Writing A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=fje-z2eW2A0',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/writing-a-z-teacher-support?cache=0',
    Videocategories: 'Writing A-Z',
    YTandVimeoLinks: 'https://vimeo.com/838362927',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/writing-a-z-handwriting-worksheet-creator?cache=0',
    Videocategories: 'Writing A-Z',
    YTandVimeoLinks: 'https://vimeo.com/882950219',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/writing-a-z-overview?cache=0',
    Videocategories: 'Writing A-Z',
    YTandVimeoLinks: 'https://vimeo.com/822106417',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/writing-a-z-student-management-and-reports?cache=0',
    Videocategories: 'Writing A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=5BpzeKaYPyY&list=PLGcuN9fntXEQNRlXhy7f4dTpQtPLIp0Ye&index=10',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/writing-a-z-units-and-modules-overview?cache=0',
    Videocategories: 'Writing A-Z',
    YTandVimeoLinks: 'https://vimeo.com/838369020',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/announcing-writinga-z?cache=0',
    Videocategories: 'Writing A-Z',
    YTandVimeoLinks: 'https://vimeo.com/596109865',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: 'VAZ Videos [58]',
    Videosundercategory: '',
    Videocategories: '',
    YTandVimeoLinks: '',
    UpdatedtoEmbededvideo: '',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/vocabulary-a-z-overview?cache=0',
    Videocategories: 'Vocabulary A-Z',
    YTandVimeoLinks: 'https://vimeo.com/462771309',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/vocabulary-reading-comprehension?cache=0',
    Videocategories: 'Vocabulary A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=gDMcmnkyWNs&list=PLGcuN9fntXERKKFjiEt8NrcH3f_fI0dlO&index=2',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: 'KAZ Videos [78]',
    Videosundercategory: '',
    Videocategories: '',
    YTandVimeoLinks: '',
    UpdatedtoEmbededvideo: '',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/navegar-el-portal-de-padres-con-kids-a-z?cache=0',
    Videocategories: 'Kids A-Z',
    YTandVimeoLinks: 'https://vimeo.com/581329147',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/exploring-parent-portal-kids-a-z?cache=0',
    Videocategories: 'Kids A-Z',
    YTandVimeoLinks: 'https://vimeo.com/581323589',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/kids-a-z-overview?cache=0',
    Videocategories: 'Kids A-Z, Raz-Kids, Raz-Plus, Science A-Z, Writing A-Z',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=CKCjRo-QJl0',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/kidsaz-parent-portal-summary?cache=0',
    Videocategories: 'Kids A-Z, Raz-Kids, Raz-Plus, Science A-Z, Writing A-Z',
    YTandVimeoLinks: 'https://vimeo.com/1012121390',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: 'Funding Videos [84]',
    Videosundercategory: '',
    Videocategories: '',
    YTandVimeoLinks: '',
    UpdatedtoEmbededvideo: '',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/cares-act-funding-spanish?cache=0',
    Videocategories: 'Funding',
    YTandVimeoLinks: 'https://vimeo.com/500988662',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/cares-act-funding?cache=0',
    Videocategories: 'Funding',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=2IGysewqVXg',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/adoptaclassroom-create-project?cache=0',
    Videocategories: 'Funding',
    YTandVimeoLinks: 'https://vimeo.com/1012122818',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/walmart-grant?cache=0',
    Videocategories: 'Funding',
    YTandVimeoLinks: 'https://vimeo.com/1012123532',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/adoptaclassroom-profile?cache=0',
    Videocategories: 'Funding',
    YTandVimeoLinks: 'https://vimeo.com/1012124123',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/adoptaclassroom-buy-learningaz-resources?cache=0',
    Videocategories: 'Funding',
    YTandVimeoLinks: 'https://vimeo.com/1012124746',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: 'Testimonial Videos [90]',
    Videosundercategory: '',
    Videocategories: '',
    YTandVimeoLinks: '',
    UpdatedtoEmbededvideo: '',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/biliteracy-pershing-park?cache=0',
    Videocategories: 'Testimonials, Raz-Plus, Raz-Plus ELL',
    YTandVimeoLinks: 'https://vimeo.com/817803449',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/literacy-clear-creek?cache=0',
    Videocategories: 'Testimonials, Raz-Plus',
    YTandVimeoLinks: 'https://vimeo.com/817745793',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/vocabulary-clear-creek?cache=0',
    Videocategories: 'Testimonials, Vocabulary A-Z',
    YTandVimeoLinks: 'https://vimeo.com/819560417',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/student-testimonials-clear-creek?cache=0',
    Videocategories: 'Testimonials, Learning A-Z',
    YTandVimeoLinks: 'https://vimeo.com/820678086',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/teacher-appreciation-killeen-isd?cache=0',
    Videocategories: 'Testimonials',
    YTandVimeoLinks: 'https://vimeo.com/823464793',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/teacher-testimonials-rachal?cache=0',
    Videocategories: 'Testimonials, Reading A-Z, Raz-Kids',
    YTandVimeoLinks: 'https://vimeo.com/1012126284',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/teacher-stories-claire-hamel?cache=0',
    Videocategories: 'Testimonials',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=8eLe4ELW3yg&list=PLGcuN9fntXESilcwi3LgddujA0k4VPYTZ&index=7',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/teacher-stories-shannon-miller?cache=0',
    Videocategories: 'Testimonials',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=Eooqw8yvLec&list=PLGcuN9fntXESilcwi3LgddujA0k4VPYTZ&index=5',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/razplus-close-reading-testimonial?cache=0',
    Videocategories: 'Testimonials, Raz-Plus',
    YTandVimeoLinks: 'https://vimeo.com/1012127691',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/teacher-testimonials-lohse?cache=0',
    Videocategories: 'Testimonials, Reading A-Z',
    YTandVimeoLinks: 'https://vimeo.com/1012127211',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/teacher-stories-brandy-chase?cache=0',
    Videocategories: 'Testimonials',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=D750sOTwyno&list=PLGcuN9fntXESilcwi3LgddujA0k4VPYTZ&index=6',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/teacher-stories-rebecca-coleman?cache=0',
    Videocategories: 'Testimonials',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=i-E3M4qJGAU&list=PLGcuN9fntXESilcwi3LgddujA0k4VPYTZ&index=3',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/reading-product-testimonials?cache=0',
    Videocategories: 'Testimonials, Reading A-Z, Raz-Kids',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=lYo9yba4sJA&list=PLGcuN9fntXEQGtzMkmhdgrLietNRMgV_B&index=6&pp=iAQB',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/teacher-stories-deanna-mcfarland?cache=0',
    Videocategories: 'Testimonials',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=XfuvpBw8q8I&list=PLGcuN9fntXESilcwi3LgddujA0k4VPYTZ&index=2',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/teacher-stories-dolleen-wiltgen?cache=0',
    Videocategories: 'Testimonials',
    YTandVimeoLinks: 'https://www.youtube.com/watch?v=tXT9JGupias&list=PLGcuN9fntXESilcwi3LgddujA0k4VPYTZ&index=4',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: 'Professional Learning [100]',
    Videosundercategory: '',
    Videocategories: '',
    YTandVimeoLinks: '',
    UpdatedtoEmbededvideo: '',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/data-literacy-workshop?cache=0',
    Videocategories: 'Professional Learning',
    YTandVimeoLinks: 'https://vimeo.com/543234725',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/easy-fun-highlight?cache=0',
    Videocategories: 'Professional Learning',
    YTandVimeoLinks: 'https://youtu.be/v5UdTyIm018',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/easy-fun-getting-started-rostering?cache=0',
    Videocategories: 'Professional Learning',
    YTandVimeoLinks: 'https://youtu.be/3Hzn8UL3QJ8',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'http://learninga-z.com/site/resources/videos/easy-fun-lesson-plans-resources?cache=0',
    Videocategories: 'Professional Learning',
    YTandVimeoLinks: 'https://youtu.be/0U77ZPgB0X0',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/easy-fun-student-engagement?cache=0',
    Videocategories: 'Professional Learning',
    YTandVimeoLinks: 'https://youtu.be/lFgLBPBdj0Y',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://www.learninga-z.com/site/resources/videos/easy-fun-professional-development?cache=0',
    Videocategories: 'Professional Learning',
    YTandVimeoLinks: 'https://youtu.be/3ksPV3x_NYI',
    UpdatedtoEmbededvideo: 'Yes',
  },
  {
    Parent: '',
    Subcategory: '',
    Videosundercategory: 'https://learninga-z.com/site/resources/videos/easy-fun-reporting?cache=0',
    Videocategories: 'Professional Learning',
    YTandVimeoLinks: 'https://youtu.be/2mL2ZzFzXqM',
    UpdatedtoEmbededvideo: 'Yes',
  },
];

export const videoThumbnails = [{"src":"/user_area/content_media/raw/350902-essentials-laz-5-edweek-thumbnail.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/sor-essentials"},
  {"src":"/user_area/content_media/raw/what-is-learninga-z.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/what-is-learningaz"},
  {"src":"/user_area/content_media/raw/pershing-park-story.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/biliteracy-pershing-park"},
  {"src":"/user_area/content_media/raw/clear-creek-story.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/literacy-clear-creek"},
  {"src":"/user_area/content_media/raw/vocabulary-clear-creek.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/vocabulary-clear-creek"},
  {"src":"/user_area/content_media/raw/student-testimonials-clear-creek.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/student-testimonials-clear-creek"},
  {"src":"/user_area/content_media/raw/appreciating-teachers-killeen-isd.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/teacher-appreciation-killeen-isd"},
  {"src":"/user_area/content_media/raw/raz-plus-espanol-overview.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-espanol-overview"},
  {"src":"/user_area/content_media/raw/powerful-duo-literacy-block.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/powerful-duo-literacy-block"},
  {"src":"/user_area/content_media/raw/foundationsa-z-overview.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/foundationsa-z-overview"},
  {"src":"/user_area/content_media/raw/2205_FAZTestimonials_JordanSnyder_Master_FAZTestimonial_FirstFrame.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/first-grade-teacher-foundations-a-z"},
  {"src":"/user_area/content_media/raw/2205_FAZTestimonials_TimRasinski.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/rasinski-elephant-in-the-classroom"},
  {"src":"/user_area/content_media/raw/burkins-yates-elephant-in-the-classroom.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/burkins-yates-elephant-in-the-classroom"},
  {"src":"/user_area/content_media/raw/jilliam-joe-elephant-in-the-classroom.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/jilliam-joe-elephant-in-the-classroom"},
  {"src":"/user_area/content_media/raw/easy-fun-highlight.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/easy-fun-highlight"},
  {"src":"/user_area/content_media/raw/easy-fun-getting-started-rostering.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/easy-fun-getting-started-rostering"},
  {"src":"/user_area/content_media/raw/FAZ-Knowledge-Building-Still.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/integrated-knowledge-building-in-foundations-a-z"},
  {"src":"/user_area/content_media/raw/easy-fun-lesson-plans-resources.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/easy-fun-lesson-plans-resources"},
  {"src":"/user_area/content_media/raw/learning-a-z-glance.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/learning-a-z-glance"},
  {"src":"/user_area/content_media/raw/easy-fun-student-engagement.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/easy-fun-student-engagement"},
  {"src":"/user_area/content_media/raw/easy-fun-professional-development.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/easy-fun-professional-development"},
  {"src":"/user_area/content_media/raw/summer-learning-scavenger-hunt.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/summer-learning-scavenger-hunt"},
  {"src":"/user_area/content_media/raw/summer-learning-word-work.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/summer-learning-word-work"},
  {"src":"/user_area/content_media/raw/summer-learning-read-alouds.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/summer-learning-read-alouds"},
  {"src":"/user_area/content_media/raw/summer-learning-writing.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/summer-learning-writing"},
  {"src":"/user_area/content_media/raw/summer-learning-print-rich-environments.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/summer-learning-print-rich-environments"},
  {"src":"/user_area/content_media/raw/summer-learning-reading-strategies.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/summer-learning-reading-strategies"},
  {"src":"/user_area/content_media/raw/summer-learning-non-fiction.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/summer-learning-non-fiction"},
  {"src":"/user_area/content_media/raw/following-an-author.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/summer-learning-following-an-author"},
  {"src":"/user_area/content_media/raw/summer-learning-school-home-connection.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/summer-learning-school-home-connection"},
  {"src":"/user_area/content_media/raw/summer-learning-reading-everyday.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/summer-learning-reading-everyday"},
  {"src":"/user_area/content_media/raw/easy-fun-reporting.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/easy-fun-reporting"},
  {"src":"/user_area/content_media/raw/explorezone.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/foundationsa-z-explore-zone"},
  {"src":"/user_area/content_media/raw/making-learning-a-z-book.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/making-learning-a-z-book"},
  {"src":"/user_area/content_media/raw/razplusoverviewthumbnail.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-essentials"},
  {"src":"/user_area/content_media/raw/Claudia-Arroyave-Koleia-Bungard-Thumbnail.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/spanish-book-author-claudia"},
  {"src":"/user_area/content_media/raw/introducing-foundationsa-z.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/introducing-foundationsa-z"},
  {"src":"/user_area/content_media/raw/Tonya-Torres-Thumbnail.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/spanish-book-author-tanya"},
  {"src":"/user_area/content_media/raw/Jorge-Mejia-Thumbnail.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/spanish-book-author-jorge"},
  {"src":"/user_area/content_media/raw/reading-product-testimonials.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/reading-product-testimonials"},
  {"src":"/user_area/content_media/raw/teacher-stories-claire-hamel.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/teacher-stories-claire-hamel"},
  {"src":"/user_area/content_media/raw/teacher-stories-shannon-miller.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/teacher-stories-shannon-miller"},
  {"src":"/user_area/content_media/raw/teacher-stories-brandy-chase.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/teacher-stories-brandy-chase"},
  {"src":"/user_area/content_media/raw/teacher-stories-rebecca-coleman.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/teacher-stories-rebecca-coleman"},
  {"src":"/user_area/content_media/raw/teacher-stories-deanna-mcfarland.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/teacher-stories-deanna-mcfarland"},
  {"src":"/user_area/content_media/raw/teacher-stories-dolleen-wiltgen.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/teacher-stories-dolleen-wiltgen"},
  {"src":"/user_area/content_media/raw/teacher-testimonial-lohse.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/teacher-testimonials-lohse"},
  {"src":"/user_area/content_media/raw/teacher-testimonial-rachal.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/teacher-testimonials-rachal"},
  {"src":"/user_area/content_media/raw/razplus-close-reading-testimonial.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/razplus-close-reading-testimonial"},
  {"src":"/user_area/content_media/raw/731-raz-plus-glance.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-at-a-glance"},
  {"src":"/user_area/content_media/raw/razplus-reading-copilot.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/razplus-reading-copilot"},
  {"src":"/user_area/content_media/raw/raz-plus-reading-instruction.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-reading-instruction"},
  {"src":"/user_area/content_media/raw/raz-plus-close-reading.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-close-reading"},
  {"src":"/user_area/content_media/raw/raz-plus-project-based-learning.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-project-based-learning"},
  {"src":"/user_area/content_media/raw/meaningful-conversations.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/meaningful-conversations"},
  {"src":"/user_area/content_media/raw/raz-plus-nwea-map-growth.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-nwea-map-growth"},
  {"src":"/user_area/content_media/raw/raz-plus-pbl-classroom.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-pbl-classroom"},
  {"src":"/user_area/content_media/raw/raz-plus-summer-school.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-summer-school"},
  {"src":"/user_area/content_media/raw/raz-plus-etools.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-etools"},
  {"src":"/user_area/content_media/raw/raz-plus-paired-books.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-paired-book"},
  {"src":"/user_area/content_media/raw/razpluselleditionvideo.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-ell-edition-overview"},
  {"src":"/user_area/content_media/raw/raz-plus-argumentation.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-argumentation"},
  {"src":"/user_area/content_media/raw/raz-plus-authentic-spanish.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-authentic-spanish"},
  {"src":"/user_area/content_media/raw/razplus-spanish-closereadingpacks.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/razplus-spanish-closereadingpacks"},
  {"src":"/user_area/content_media/raw/raz-plus-connected-classroom.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-connected-classroom"},
  {"src":"/user_area/content_media/raw/raz-plus-close-read-summary.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-close-read-summary"},
  {"src":"/user_area/content_media/raw/domore.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-decodables"},
  {"src":"/user_area/content_media/raw/rpvideo.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-content-area"},
  {"src":"/user_area/content_media/raw/Screenshot2024-03-20at1.44.00PM.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-plus-multilingual"},
  {"src":"/user_area/content_media/raw/482-reading-a-z-overview.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/reading-a-z-overview"},
  {"src":"/user_area/content_media/raw/readinga-z-close-reading.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/reading-a-z-close-reading"},
  {"src":"/user_area/content_media/raw/readinga-z-comprehension-packs.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/reading-a-z-comprehension-packs"},
  {"src":"/user_area/content_media/raw/readinga-z-fluency-practice.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/reading-a-z-fluency-practice"},
  {"src":"/user_area/content_media/raw/readinga-z-find-resources.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/readinga-z-find-resources"},
  {"src":"/user_area/content_media/raw/readinga-z-pairedbook.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/readinga-z-paired-book"},
  {"src":"/user_area/content_media/raw/readinga-z-pbl-classroom.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/reading-a-z-pbl-classroom"},
  {"src":"/user_area/content_media/raw/readinga-z-project-based-learning.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/readinga-z-project-based-learning"},
  {"src":"/user_area/content_media/raw/readinga-z-summer-school.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/readinga-z-summer-school"},
  {"src":"/user_area/content_media/raw/hollowkidseriesvide.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/hollow-kids-series"},
  {"src":"/user_area/content_media/raw/hollow-kids-finale-video.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/hollow-kids-finale"},
  {"src":"/user_area/content_media/raw/razkidsglance.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-kids-at-a-glance"},
  {"src":"/user_area/content_media/raw/raz-kids-ebook-tools.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/raz-kids-ebook-tools"},
  {"src":"/user_area/content_media/raw/student-portal-features-incentives.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/student-portal-features-incentives"},
  {"src":"/user_area/content_media/raw/sazthumb.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/science-in-the-news"},
  {"src":"/user_area/content_media/raw/science-a-z-overview.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/science-a-z-overview"},
  {"src":"/user_area/content_media/raw/science-a-z-glance.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/science-a-z-at-a-glance"},
  {"src":"/user_area/content_media/raw/saz-adventures.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/saz-adventures"},
  {"src":"/user_area/content_media/raw/interactive-science-lessons.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/interactive-science-lessons"},
  {"src":"/user_area/content_media/raw/science-project-based-learning.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/science-project-based-learning"},
  {"src":"/user_area/content_media/raw/scienceaz-storylines.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/scienceaz-storylines"},
  {"src":"/user_area/content_media/raw/waltsized.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/meetwaltwritingandlearningtogether"},
  {"src":"/user_area/content_media/raw/writinga-z-overview.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/writing-a-z-overview"},
  {"src":"/user_area/content_media/raw/wazhandwritingworksheet.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/writing-a-z-handwriting-worksheet-creator"},
  {"src":"/user_area/content_media/raw/WAZunitsandmodulesoverview.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/writing-a-z-units-and-modules-overview"},
  {"src":"/user_area/content_media/raw/WritingA-ZLessonPlans.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/writing-a-z-lesson-plans"},
  {"src":"/user_area/content_media/raw/WritingA-ZTeacherSupport.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/writing-a-z-teacher-support"},
  {"src":"/user_area/content_media/raw/WritingA-ZStudentManagementandReports.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/writing-a-z-student-management-and-reports"},
  {"src":"/user_area/content_media/raw/vocabulary-a-z-overview.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/vocabulary-a-z-overview"},
  {"src":"/user_area/content_media/raw/vocabulary-reading-comprehension.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/vocabulary-reading-comprehension"},
  {"src":"/user_area/content_media/raw/kidsazoverview.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/kids-a-z-overview"},
  {"src":"/user_area/content_media/raw/kidsaz-parent-portal-summary.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/kidsaz-parent-portal-summary"},
  {"src":"/user_area/content_media/raw/cares-act-funding.png?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/cares-act-funding"},
  {"src":"/user_area/content_media/raw/walmart-grant.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/walmart-grant"},
  {"src":"/user_area/content_media/raw/adoptaclassroom-video.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/adoptaclassroom-profile"},
  {"src":"/user_area/content_media/raw/adoptaclassroom-create-project.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/adoptaclassroom-create-project"},
  {"src":"/user_area/content_media/raw/adoptaclassroom-buy-learningaz-resources.jpg?w=600&quality=70&h=400&format=jpg&mode=crop&scale=both","href":"/site/resources/videos/adoptaclassroom-buy-learningaz-resources"}];
  
